### ISSUE TITLE
Documentation of training procedure

### ISSUE THREAD

**Issue by ftyers** [SUTDNLP/ZGen#4]
Hello all,

We would like to use ZGen to linearise dependency trees, that is, our input is an unordered tree, for example:

```
<NODE lem="love" si="root">
  <NODE lem="Mary" si="nsubj"/>
  <NODE lem="beer" si="obj"/>
</NODE>
```

And the output is a sequence of tokens in order, e.g. "Mary love beer".

I have read the documentation, but I can't find out how I would train such a model. 

Some specific questions:

1. What does `-1` and `1` mean in the constraints format ? Is `-1` = head and `1` = dependent?
2. Could the constraints be extracted from a treebank ? 

If there is some other documentation and I've missed it, apologies!

**Comment by ratishsp** [comment]
__Ms._Haag__ NP 1 N
plays VBZ -1 N
__Elianti__ NP 1 N
. . 1 N

1. Yes, -1 is head. 1= node index of the parent. It is zero-indexed. So in the example, Ms_haag, Elianti and . have parent as plays.
2. The constraints could be extracted from treebank. ZGen expects input in the stated format. You could preprocess the treebank input to ZGen input

-Ratish

**Comment by ftyers** [comment]
So if my input is a full dependency tree, should I split the tree into subtrees or can I just give the full tree as a single constraint (with index of 1 for leaf nodes and then nodes with -n for heads ?)

Another question I had: Is the linear order determined by the order in the file ? e.g. if I had 

```
_Ms.Haag NP 1 N
Elianti NP 1 N
plays VBZ -1 N
. . 1 N
```

Would it be linearised as "Ms. Haag Elianti plays" ? So, in my example, the constraint would be:

```
_ _ 1 nsubj
_ _ -1 root
_ _ 1 obj
```

?

**Comment by ratishsp** [comment]
I think there is slight confusion. Let me restate what those integers mean with another example

the	1
boy	2
went	-1
home	2

This input means: 'went' is the root of dependency tree, 'boy' and 'home' are child nodes of 'went', 'the' is child of 'boy'. The indices are zero-indexed.

You can give the full tree as a single constraint

**Comment by ftyers** [comment]
Ok, so the tree is:

```
                      |
-1                went
                      |
         |-----------------------|
         |                          |
2      boy                   home
         |
1      the
```

If so, I don't get the numbering. They are zero-indexed with respect to what ? I'm sorry if I'm being a bit slow here! 

Also, is the linear order determined by the order in the file ? So:

1st word: the; 2nd word: boy; 3rd word: went; 4th word: home

**Comment by ratishsp** [comment]
No need to be sorry!!
The tree is as you have understood and painted.
Zero-indexed with respect to the order in the input record:

0th word: the
1st word: boy
2nd word: went
3rd word: home

[node index]        [word]    [parent (word)]
0                        the       1 (boy)
1                        boy      2 (went)
2                        went    -1 (root)
3                        home   2  (went)

**Comment by ftyers** [comment]
Ok, so let's see if I get it, let's say I have the following unordered input tree:

```
           drank/VERB
       _______|____________________________________________
      |                              |                      |
   Mary/NOUN                     beer/NOUN          yesterday/ADV
                                     |
                                   a/DET

root(drank)
nsubj(drank, Mary)
obj(drank, beer)
det(beer, a)
advmod(drank, yesterday)
```
And I want the output linearisation "Yesterday Mary drank a beer"

The (delexicalised) tree constraint could be:

```
# forms, postag, head, deprel
_    _   2   advmod
_    _   2   nsubj
_    _   -1  root
_    _   4   det
_    _   2   obj
```

?

**Comment by ratishsp** [comment]
Yes. The tree constraints are correct. 
forms, postag, head, deprel
yesterday    _   2   advmod
Mary    _   2   nsubj
drank    _   -1  root
a    _   4   det
beer    _   2   obj


The input is of the same format as conll or conll-u format for HEAD and DEPREL. Except that the indices are zero indexed and root is -1
