### ISSUE TITLE
Error when running ZGen -test

### ISSUE THREAD

**Issue by bujol12** [SUTDNLP/ZGen#6]
Hello,

I'm trying to run ZGen with this as my input.in file:

`
__Ms._Haag__ _ 1 N `
`plays _ -1 N`
`__Elianti__ NP -1 _`
`. . 1 N
`

Using this command:
`./bin/ZGen_SR test \`
 `       --type  none \`
 `       --model /path/to/your/model \`
  `      --input /path/to/your/input_file \`
  `      --posdict /path/to/your/postag_dict`

Using the model linked in the documentation.

And my output is this:
`2017-01-06 23:11:21 [warning] parseopt: postag dict is specified.`
`2017-01-06 23:11:21 [info] `
`2017-01-06 23:11:21 [info] ZGen::shift-reduce linearizer << TEST >> 0.2.0`
`2017-01-06 23:11:21 [info] ----------------------------------------------`
`2017-01-06 23:11:21 [info] Experiment 22-3.1 - All feat with S0 lookahead feat`
`2017-01-06 23:11:21 [warning] Pipe: ngram model doesn't exist.`
`terminate called after throwing an instance of 'boost::archive::archive_exception'`
 ` what():  input stream error`
`Aborted (core dumped)`

Do you have any ideas how to fix it? Am I doing something wrong?

**Comment by ratishsp** [comment]
Hi,
I believe the issue is because of the difference in version of the trained model. The linked model is consistent with an earlier version of the code. I have trained a full tree linearizer model with latest code at https://drive.google.com/open?id=0B2n3SQth3VS2aXF2NnVNdWhyUTA

**Comment by bujol12** [comment]
Hi,

Unfortunately, it does not help, I still get the same error...

Any other ideas what may cause that?

Maybe I can try training the lineariser on my own?

I assume the command is: 
`/bin/ZGen_SR learn --model path/to/model_output --type full/partial/none --input path/to/Treebank_in_the_ZGen_Format`

Could you please confirm that I'm right? What about the reference argument?

Moreover, I assume that my input sentences are separated by the newline sign?

**Comment by ratishsp** [comment]
I will check the issue regarding testing with the trained model.
Yes, you can try training the linearizer on your own.
The command is correct.
The reference argument is the path for gold input file with full pos and dependencies.
The input file may have full or partial or no dependencies depending on the type you select.
Yes, input sentences need to separated by newline

**Comment by bujol12** [comment]
What do you mean by the "gold input file with pos and dependencies"? Is just a file with a sentence like:
`__Ms._Haag__ NP 1 N`
`plays VBZ -1 N`
`__Elianti__ NP 1 N`
`. . 1 N`

?

**Comment by ratishsp** [comment]
Yes, the example is correct. As you observe, POS and dependency information for each node is available for gold input file.
